# 可选择的数据集名称
dataset_name : nsd # algnauts nsd nod

# 文件路径
path:
  parent: ".."
  dataset: "dataset"
  algnauts: "algnauts_2023_challenge_data"
  nsd: "NSD"
  nod: "NOD"

# 训练模型时的超参数
train:
  batch_size: null

# 手动选择受试者
subjects:
  algnauts: # id 1~8
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  nod: # id 1~30
    - 1 
    - 2 
    - 3 
    - 4 
    - 5 
    - 6 
    - 7 
    - 8 
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15 
    - 16 
    - 17 
    - 18 
    - 19 
    - 20 
    - 21 
    - 22 
    - 23 
    - 24 
    - 25 
    - 26 
    - 27 
    - 28 
    - 29 
    - 30
  nsd: # id 1~8
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8